version: '3.7'

services:
  advcbv:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./advcbv:/advcbv
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
